-- Seed data for quote items (products and services in quotes)
-- Using test organization and user IDs

-- Clean up existing quote items data
TRUNCATE TABLE quote_items CASCADE;

-- Get reference IDs for quotes, products, and services
WITH quote_refs AS (
  SELECT id, quote_number FROM quotes WHERE organization_clerk_id = 'org_31Vn5FBdgy2geINV5ggcrmM7Oqi'
),
product_refs AS (
  SELECT id, name, sku, price FROM products WHERE organization_clerk_id = 'org_31Vn5FBdgy2geINV5ggcrmM7Oqi'
),
service_refs AS (
  SELECT id, name, rate FROM services WHERE organization_clerk_id = 'org_31Vn5FBdgy2geINV5ggcrmM7Oqi' AND status = 'active'
)

-- Insert quote items with realistic IT equipment and services
INSERT INTO quote_items (
  quote_id,
  item_type,
  product_id,
  service_id,
  name,
  description,
  quantity,
  unit_price,
  discount_type,
  discount_value,
  organization_clerk_id
)
SELECT 
  quote_id,
  item_type,
  product_id,
  service_id,
  item_name,
  item_description,
  quantity,
  unit_price,
  discount_type,
  discount_value,
  'org_31Vn5FBdgy2geINV5ggcrmM7Oqi'
FROM (
  VALUES
    -- QT-2024-001: TechCorp IT Infrastructure Upgrade (DRAFT)
    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-001'), 
     'product', 
     (SELECT id FROM product_refs WHERE sku = 'DELL-LAT-5540'), 
     NULL, 
     'Business Laptop - Dell Latitude 5540', 
     'High-performance business laptop with 16GB RAM, 512GB SSD', 
     15, 
     1799.00, 
     'percentage', 
     5.0),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-001'), 
     'product', 
     (SELECT id FROM product_refs WHERE sku = 'DELL-P2423DE'), 
     NULL, 
     'Dell P2423DE Monitor', 
     '24" QHD USB-C Hub Monitor for business workstations', 
     15, 
     599.99, 
     'percentage', 
     5.0),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-001'), 
     'service', 
     NULL, 
     (SELECT id FROM service_refs WHERE name = 'Hardware Installation'), 
     'Hardware Installation', 
     'Complete setup and configuration of all equipment', 
     40, 
     95.00, 
     NULL, 
     NULL),

    -- QT-2024-002: Sarah Johnson Consulting SMALL BUSINESS SETUP (SENT)
    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-002'), 
     'product', 
     (SELECT id FROM product_refs WHERE sku = 'DELL-OPT-7010'), 
     NULL, 
     'Dell OptiPlex 7010 Desktop', 
     'Business desktop for office productivity', 
     3, 
     1299.00, 
     'percentage', 
     8.0),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-002'), 
     'product', 
     (SELECT id FROM product_refs WHERE sku = 'HP-E27-G5'), 
     NULL, 
     'HP E27 G5 Monitor', 
     '27" FHD IPS Monitor for office use', 
     3, 
     379.99, 
     'percentage', 
     8.0),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-002'), 
     'service', 
     NULL, 
     (SELECT id FROM service_refs WHERE name = 'Network Setup'), 
     'Network Setup', 
     'Small office network configuration', 
     1, 
     1200.00, 
     NULL, 
     NULL),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-002'), 
     'service', 
     NULL, 
     (SELECT id FROM service_refs WHERE name = 'User Training'), 
     'User Training', 
     'Basic computer and network usage training', 
     4, 
     110.00, 
     NULL, 
     NULL),

    -- QT-2024-003: Michael Chen Cloud Migration (SENT)
    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-003'), 
     'service', 
     NULL, 
     (SELECT id FROM service_refs WHERE name = 'Cloud Migration'), 
     'Cloud Migration', 
     'Complete migration to cloud infrastructure', 
     1, 
     3500.00, 
     'percentage', 
     10.0),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-003'), 
     'service', 
     NULL, 
     (SELECT id FROM service_refs WHERE name = 'Data Migration'), 
     'Data Migration', 
     'Secure transfer of all company data', 
     1, 
     1800.00, 
     NULL, 
     NULL),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-003'), 
     'service', 
     NULL, 
     (SELECT id FROM service_refs WHERE name = 'Administrator Training'), 
     'Administrator Training', 
     'Training for cloud system management', 
     1, 
     800.00, 
     NULL, 
     NULL),

    -- QT-2024-004: Lisa Rodriguez Medical Practice SECURITY UPGRADE (SENT)
    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-004'), 
     'product', 
     (SELECT id FROM product_refs WHERE sku = 'HP-ELITEBOOK-850'), 
     NULL, 
     'HP EliteBook 850 G10', 
     '15.6" enterprise laptop for medical staff', 
     4, 
     2199.00, 
     'percentage', 
     7.0),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-004'), 
     'service', 
     NULL, 
     (SELECT id FROM service_refs WHERE name = 'Security Assessment'), 
     'Security Assessment', 
     'HIPAA compliance security audit', 
     1, 
     2500.00, 
     NULL, 
     NULL),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-004'), 
     'service', 
     NULL, 
     (SELECT id FROM service_refs WHERE name = 'User Training'), 
     'User Training', 
     'Security awareness and HIPAA compliance training', 
     12, 
     110.00, 
     NULL, 
     NULL),

    -- QT-2024-005: Emma Wilson Creative Studio WORKSTATION SETUP (VIEWED)
    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-005'), 
     'product', 
     (SELECT id FROM product_refs WHERE sku = 'ASUS-PG279QM'), 
     NULL, 
     'ASUS ROG Swift PG279QM', 
     '27" WQHD 240Hz Monitor for creative work', 
     6, 
     899.99, 
     'percentage', 
     8.0),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-005'), 
     'service', 
     NULL, 
     (SELECT id FROM service_refs WHERE name = 'Software Installation & Configuration'), 
     'Software Installation & Configuration', 
     'Installation of Creative Suite and design software', 
     12, 
     85.00, 
     NULL, 
     NULL),

    -- QT-2024-006: David Park Consulting Office (APPROVED)
    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-006'), 
     'product', 
     (SELECT id FROM product_refs WHERE sku = 'DELL-LAT-5540'), 
     NULL, 
     'Dell Latitude 5540', 
     'Standard business laptop for consulting work', 
     6, 
     1799.00, 
     'percentage', 
     8.0),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-006'), 
     'service', 
     NULL, 
     (SELECT id FROM service_refs WHERE name = 'IT Consultation'), 
     'IT Consultation', 
     'Strategic IT planning for new office setup', 
     8, 
     200.00, 
     NULL, 
     NULL),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-006'), 
     'service', 
     NULL, 
     (SELECT id FROM service_refs WHERE name = 'Monthly IT Maintenance'), 
     'Monthly IT Maintenance', 
     'Ongoing IT support contract (first year)', 
     12, 
     450.00, 
     'percentage', 
     5.0),

    -- QT-2024-007: Alex Thompson Freelancer Setup (APPROVED)
    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-007'), 
     'product', 
     (SELECT id FROM product_refs WHERE sku = 'HP-ELITE-800'), 
     NULL, 
     'HP EliteDesk 800 G9', 
     'High-performance desktop for software development', 
     1, 
     1599.00, 
     NULL, 
     NULL),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-007'), 
     'product', 
     (SELECT id FROM product_refs WHERE sku = 'DELL-P2423DE'), 
     NULL, 
     'Dell P2423DE Monitor', 
     'Dual monitor setup for development', 
     2, 
     599.99, 
     NULL, 
     NULL),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-007'), 
     'service', 
     NULL, 
     (SELECT id FROM service_refs WHERE name = 'Hardware Installation'), 
     'Hardware Installation', 
     'Setup and configuration of development environment', 
     4, 
     95.00, 
     NULL, 
     NULL),

    -- QT-2024-008: Dr. Jennifer Martinez HIPAA Setup (DECLINED)  
    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-008'), 
     'product', 
     (SELECT id FROM product_refs WHERE sku = 'DELL-LAT-5540'), 
     NULL, 
     'Dell Latitude 5540', 
     'HIPAA-compliant laptop with encryption', 
     4, 
     1799.00, 
     'percentage', 
     5.0),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-008'), 
     'service', 
     NULL, 
     (SELECT id FROM service_refs WHERE name = 'Security Assessment'), 
     'Security Assessment', 
     'HIPAA compliance audit and setup', 
     1, 
     2500.00, 
     NULL, 
     NULL),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-008'), 
     'service', 
     NULL, 
     (SELECT id FROM service_refs WHERE name = 'User Training'), 
     'User Training', 
     'HIPAA compliance and security training', 
     8, 
     110.00, 
     NULL, 
     NULL),

    -- QT-2024-009: Robert Kim Server Replacement (EXPIRED)
    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-009'), 
     'product', 
     (SELECT id FROM product_refs WHERE sku = 'DELL-R650'), 
     NULL, 
     'Dell PowerEdge R650', 
     'Enterprise server for business critical applications', 
     2, 
     8999.99, 
     'percentage', 
     12.0),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-009'), 
     'service', 
     NULL, 
     (SELECT id FROM service_refs WHERE name = 'Hardware Installation'), 
     'Hardware Installation', 
     'Server installation and configuration', 
     16, 
     95.00, 
     NULL, 
     NULL),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-009'), 
     'service', 
     NULL, 
     (SELECT id FROM service_refs WHERE name = 'Data Migration'), 
     'Data Migration', 
     'Migration of all data to new server', 
     1, 
     1800.00, 
     NULL, 
     NULL),

    -- QT-2024-010: Global Enterprise Inc Network Upgrade (CONVERTED) 
    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-010'), 
     'product', 
     (SELECT id FROM product_refs WHERE sku = 'CISCO-2960X-24'), 
     NULL, 
     'Cisco Catalyst 2960X-24TS-L', 
     'Managed Ethernet switch for enterprise network', 
     6, 
     1299.99, 
     'percentage', 
     15.0),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-010'), 
     'service', 
     NULL, 
     (SELECT id FROM service_refs WHERE name = 'Network Setup'), 
     'Network Setup', 
     'Complete enterprise network installation', 
     1, 
     1200.00, 
     NULL, 
     NULL),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-010'), 
     'service', 
     NULL, 
     (SELECT id FROM service_refs WHERE name = 'Administrator Training'), 
     'Administrator Training', 
     'Network management training for IT staff', 
     2, 
     800.00, 
     'percentage', 
     10.0),

    -- QT-2024-011: Startup Solutions Co Emergency Response (DRAFT - RECENT)
    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-011'), 
     'service', 
     NULL, 
     (SELECT id FROM service_refs WHERE name = 'Emergency Support'), 
     'Emergency Support', 
     'After-hours critical system recovery', 
     12, 
     180.00, 
     NULL, 
     NULL),

    ((SELECT id FROM quote_refs WHERE quote_number = 'QT-2024-011'), 
     'service', 
     NULL, 
     (SELECT id FROM service_refs WHERE name = 'Data Recovery'), 
     'Data Recovery', 
     'Recovery of corrupted business files', 
     1, 
     500.00, 
     NULL, 
     NULL)

) AS item_data(quote_id, item_type, product_id, service_id, item_name, item_description, quantity, unit_price, discount_type, discount_value);